# Fetch coffee roasters from Wikidata via SPARQL.
# Output: src/data/coffee-roasters-wikidata.js (auto-generated, do not hand-edit)
#
# Wikidata is CC0 (public domain). Source attribution is still encoded in
# every record and surfaced in the UI, consistent with Guapa's
# "never source of truth" principle.
#
# Run from anywhere; script resolves its own directory.

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir '..\..')
$workDir = Join-Path $scriptDir '.work'
$jsonPath = Join-Path $workDir 'wikidata-roasters.json'
$outPath = Join-Path $repoRoot 'src\data\coffee-roasters-wikidata.js'

New-Item -ItemType Directory -Force -Path $workDir | Out-Null

# SPARQL query:
#   P31 = instance of
#   P279* = zero or more subclass-of hops
#   Q2363097  = coffee roaster (company)
#   P571 = inception (founded date)
#   P17  = country
#   P159 = headquarters location
#   P856 = official website
#   P2003 = Instagram username
#   P154 = logo image (Commons filename)
#   P112 = founded by
$sparql = @'
SELECT DISTINCT ?r ?rLabel ?founded ?countryLabel ?hqLabel ?website ?instagram ?logo ?founderLabel WHERE {
  ?r wdt:P31 wd:Q2363097 .
  OPTIONAL { ?r wdt:P571 ?founded . }
  OPTIONAL { ?r wdt:P17   ?country . }
  OPTIONAL { ?r wdt:P159  ?hq . }
  OPTIONAL { ?r wdt:P856  ?website . }
  OPTIONAL { ?r wdt:P2003 ?instagram . }
  OPTIONAL { ?r wdt:P154  ?logo . }
  OPTIONAL { ?r wdt:P112  ?founder . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY ?rLabel
'@

Write-Host "[1/2] Querying Wikidata SPARQL endpoint..."
$encoded = [System.Uri]::EscapeDataString($sparql)
$url = "https://query.wikidata.org/sparql?query=$encoded&format=json"
$headers = @{
    'User-Agent' = 'GuapaDataBot/1.0 (https://guapa.space; eewilliamsremote@gmail.com) PowerShell'
    'Accept' = 'application/sparql-results+json'
}
# PS 5.1 Invoke-RestMethod mis-decodes UTF-8 when the server omits charset in
# Content-Type. Use Invoke-WebRequest and decode raw bytes ourselves.
$raw = Invoke-WebRequest -Uri $url -Headers $headers -TimeoutSec 120 -UseBasicParsing
$json = [System.Text.Encoding]::UTF8.GetString($raw.RawContentStream.ToArray())
$resp = $json | ConvertFrom-Json
$bindings = $resp.results.bindings
Write-Host "  Got $($bindings.Count) raw bindings"

# Collapse duplicates: multiple founders/countries produce multiple rows per roaster.
# Key by QID, merge founder labels into an array.
$byQid = @{}
foreach ($b in $bindings) {
    $qid = ($b.r.value -replace '.*/', '')
    if (-not $byQid.ContainsKey($qid)) {
        $foundedYear = $null
        if ($b.founded) { $foundedYear = [int]($b.founded.value.Substring(0, 4)) }
        $byQid[$qid] = [ordered]@{
            qid       = $qid
            name      = if ($b.rLabel) { $b.rLabel.value } else { $qid }
            founded   = $foundedYear
            country   = if ($b.countryLabel) { $b.countryLabel.value } else { $null }
            hq        = if ($b.hqLabel)      { $b.hqLabel.value }      else { $null }
            website   = if ($b.website)      { $b.website.value }      else { $null }
            instagram = if ($b.instagram)    { $b.instagram.value }    else { $null }
            logo      = if ($b.logo)         { $b.logo.value }         else { $null }
            founders  = @()
        }
    }
    if ($b.founderLabel -and $b.founderLabel.value) {
        $rec = $byQid[$qid]
        if ($rec.founders -notcontains $b.founderLabel.value) {
            $rec.founders += $b.founderLabel.value
        }
    }
}

# Filter out entries with no English label (name === qid) — Wikidata returns the
# QID as the label when no English rdfs:label exists, producing useless records.
$roasters = $byQid.Values | Where-Object { $_.name -ne $_.qid } | Sort-Object { $_.name }
Write-Host "  $($roasters.Count) unique roasters after dedupe + label filter"

$roasters | ConvertTo-Json -Depth 5 | Set-Content $jsonPath -Encoding UTF8

Write-Host "[2/2] Emitting coffee-roasters-wikidata.js..."

function EscJs($s) {
    if ($null -eq $s) { return 'null' }
    $esc = $s -replace '\\', '\\\\' -replace "'", "\'"
    return "'$esc'"
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// coffee-roasters-wikidata.js - auto-generated by scripts/coffee-roasters/fetch-wikidata.ps1')
[void]$sb.AppendLine('// Source: Wikidata (https://www.wikidata.org/)')
[void]$sb.AppendLine('// License: CC0 1.0 Universal (public domain)')
[void]$sb.AppendLine('// Query: entities that are instance-of Q2363097 (coffee roaster / roasting company)')
[void]$sb.AppendLine('// Do not hand-edit - regenerate to refresh. The composed multi-source dataset')
[void]$sb.AppendLine('// lives in src/data/coffee-roasters.js.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("export const WIKIDATA_FETCHED_ON = '$(Get-Date -Format 'yyyy-MM-dd')';")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// Each record: { qid, name, founded, country, hq, website, instagram, logo, founders }')
[void]$sb.AppendLine('export const WIKIDATA_ROASTERS = [')
foreach ($r in $roasters) {
    [void]$sb.AppendLine('  {')
    [void]$sb.AppendLine("    qid: $(EscJs $r.qid),")
    [void]$sb.AppendLine("    name: $(EscJs $r.name),")
    $foundedLit = if ($null -ne $r.founded) { $r.founded } else { 'null' }
    [void]$sb.AppendLine("    founded: $foundedLit,")
    [void]$sb.AppendLine("    country: $(EscJs $r.country),")
    [void]$sb.AppendLine("    hq: $(EscJs $r.hq),")
    [void]$sb.AppendLine("    website: $(EscJs $r.website),")
    [void]$sb.AppendLine("    instagram: $(EscJs $r.instagram),")
    [void]$sb.AppendLine("    logo: $(EscJs $r.logo),")
    $founderJs = ($r.founders | ForEach-Object { EscJs $_ }) -join ', '
    [void]$sb.AppendLine("    founders: [$founderJs],")
    [void]$sb.AppendLine('  },')
}
[void]$sb.AppendLine('];')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $utf8NoBom)
Write-Host "`nWrote $outPath"
Write-Host "  $($roasters.Count) roasters"
Write-Host "  With founding year: $(($roasters | Where-Object { $null -ne $_.founded }).Count)"
Write-Host "  With website: $(($roasters | Where-Object { $_.website }).Count)"
Write-Host "  With Instagram: $(($roasters | Where-Object { $_.instagram }).Count)"
