# Fetch coffee roasters from OpenStreetMap via Overpass API.
# Output: src/data/coffee-roasters-osm.js (auto-generated, do not hand-edit)
#
# OSM data is ODbL-licensed: free to use with attribution
# ("(c) OpenStreetMap contributors"). The attribution is surfaced in
# the UI via the source pill, same pattern as USDA/Conab.
#
# This pull is intentionally narrow: only nodes tagged craft=coffee_roaster
# AND with both a website and a name, to keep the catalog signal-strong.
# Thousands of OSM entries are unnamed cafes that also roast; we skip those
# because Wikidata already covers the named companies.

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir '..\..')
$workDir = Join-Path $scriptDir '.work'
$jsonPath = Join-Path $workDir 'osm-roasters.json'
$outPath = Join-Path $repoRoot 'src\data\coffee-roasters-osm.js'

New-Item -ItemType Directory -Force -Path $workDir | Out-Null

# Overpass QL: every node or way globally tagged craft=coffee_roaster
# with a name and either a website or a Wikidata qid. Output centers.
$overpass = @'
[out:json][timeout:120];
(
  node["craft"="coffee_roaster"]["name"];
  way["craft"="coffee_roaster"]["name"];
);
out center;
'@

Write-Host "[1/2] Querying Overpass API..."
$headers = @{
    'User-Agent' = 'GuapaDataBot/1.0 (https://guapa.space; eewilliamsremote@gmail.com) PowerShell'
}
$body = @{ data = $overpass }
# PS 5.1 Invoke-RestMethod mis-decodes UTF-8 when the server omits charset in
# Content-Type. Use Invoke-WebRequest and decode raw bytes ourselves.
$raw = Invoke-WebRequest -Uri 'https://overpass-api.de/api/interpreter' -Method Post -Body $body -Headers $headers -TimeoutSec 180 -UseBasicParsing
$json = [System.Text.Encoding]::UTF8.GetString($raw.RawContentStream.ToArray())
$resp = $json | ConvertFrom-Json
$elements = $resp.elements
Write-Host "  Got $($elements.Count) elements"

$records = @()
foreach ($el in $elements) {
    $tags = $el.tags
    if (-not $tags) { continue }
    $name = $tags.name
    if (-not $name) { continue }
    $lat = if ($el.type -eq 'node') { $el.lat } else { $el.center.lat }
    $lon = if ($el.type -eq 'node') { $el.lon } else { $el.center.lon }
    $records += [ordered]@{
        osmType  = $el.type
        osmId    = $el.id
        name     = $name
        website  = $tags.website
        country  = $tags.'addr:country'
        city     = $tags.'addr:city'
        wikidata = $tags.wikidata
        lat      = $lat
        lon      = $lon
    }
}

$records | ConvertTo-Json -Depth 5 | Set-Content $jsonPath -Encoding UTF8
Write-Host "  $($records.Count) named roasters with coordinates"

Write-Host "[2/2] Emitting coffee-roasters-osm.js..."

function EscJs($s) {
    if ($null -eq $s) { return 'null' }
    $esc = $s -replace '\\', '\\\\' -replace "'", "\'"
    return "'$esc'"
}

$sorted = $records | Sort-Object { $_.name }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// coffee-roasters-osm.js - auto-generated by scripts/coffee-roasters/fetch-osm.ps1')
[void]$sb.AppendLine('// Source: OpenStreetMap via Overpass API (https://overpass-api.de/)')
[void]$sb.AppendLine('// License: ODbL 1.0 (Open Database License)')
[void]$sb.AppendLine('// Attribution required: (c) OpenStreetMap contributors')
[void]$sb.AppendLine('// Query: nodes/ways tagged craft=coffee_roaster with a name')
[void]$sb.AppendLine('// Do not hand-edit - regenerate to refresh.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("export const OSM_FETCHED_ON = '$(Get-Date -Format 'yyyy-MM-dd')';")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// Each record: { osmType, osmId, name, website, country, city, wikidata, lat, lon }')
[void]$sb.AppendLine('export const OSM_ROASTERS = [')
foreach ($r in $sorted) {
    [void]$sb.AppendLine('  {')
    [void]$sb.AppendLine("    osmType: $(EscJs $r.osmType),")
    [void]$sb.AppendLine("    osmId: $($r.osmId),")
    [void]$sb.AppendLine("    name: $(EscJs $r.name),")
    [void]$sb.AppendLine("    website: $(EscJs $r.website),")
    [void]$sb.AppendLine("    country: $(EscJs $r.country),")
    [void]$sb.AppendLine("    city: $(EscJs $r.city),")
    [void]$sb.AppendLine("    wikidata: $(EscJs $r.wikidata),")
    $latStr = if ($null -ne $r.lat) { $r.lat } else { 'null' }
    $lonStr = if ($null -ne $r.lon) { $r.lon } else { 'null' }
    [void]$sb.AppendLine("    lat: $latStr,")
    [void]$sb.AppendLine("    lon: $lonStr,")
    [void]$sb.AppendLine('  },')
}
[void]$sb.AppendLine('];')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $utf8NoBom)
Write-Host "`nWrote $outPath"
Write-Host "  $($records.Count) roasters"
Write-Host "  With website: $(($records | Where-Object { $_.website }).Count)"
Write-Host "  With country tag: $(($records | Where-Object { $_.country }).Count)"
