"""Batch-fill all remaining unconfirmed artists (Eels-end of catalog)."""
import csv, io, sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

CSV_PATH = Path(__file__).parent.parent / "public" / "data" / "artist-editorial.csv"

UPDATES = {
    "EELS": ("\U0001F40D", "Mark Oliver Everett's vehicle. Beautiful Freak. Indie outsider with the saddest songs in pop."),
    "Ektomorf": ("\U0001F918", "Hungarian groove-metal. Roma identity in extreme music."),
    "Elbow": ("\U0001F303", "One Day Like This. Manchester orchestral indie. Guy Garvey's everyman gravitas."),
    "Electric Light Orchestra": ("\U0001F680", "Mr. Blue Sky. Jeff Lynne's Beatles-with-strings blueprint. Out of the Blue."),
    "Eliane Elias": ("\U0001F3B9", "Brazilian pianist and singer. Bossa-jazz without the kitsch."),
    "Elis Regina": ("\U0001F1E7\U0001F1F7", "Brazilian voice incarnate. Aguas de Marco. Died at 36, never replaced."),
    "Ella Eyre": ("\U0001F3A4", "British soul-pop firepower. Waiting All Night with Rudimental."),
    "Ella Fitzgerald": ("\U0001F451", "First Lady of Song. The Songbook series. Three octaves of perfect time."),
    "Ellie Goulding": ("✨", "Lights. Love Me Like You Do. Britain's whisper-pop biggest export."),
    "Elliott Smith": ("\U0001F312", "Either/Or. Figure 8. Whispered devastation. Portland to Oscar nomination, then gone."),
    "Elmore James": ("\U0001F3B8", "Slide-guitar king. Dust My Broom. The riff every blues player knows."),
    "Emeli Sandé": ("\U0001F3A4", "Scottish-Zambian songwriter. Read All About It. Olympic ceremony voice."),
    "Emmylou Harris": ("\U0001F33E", "Wrecking Ball. Country-folk angel. Gram Parsons's duet partner, then everyone's."),
    "Emperor": ("❄️", "Norwegian black metal. In the Nightside Eclipse. Symphonic darkness as architecture."),
    "Eric Dolphy": ("\U0001F3B7", "Bass clarinet, alto, flute. Out to Lunch. Ahead of his time, gone at 36."),
    "Ernest Tubb": ("\U0001F920", "Walking the Floor Over You. Honky-tonk pioneer."),
    "Etta James": ("\U0001F48B", "At Last. Tell Mama. Blues-soul belt that rewrote the standards."),
    "Europe": ("⚡", "The Final Countdown. Swedish hair metal's biggest single. That keyboard hook."),
    "Evanescence": ("\U0001F987", "Bring Me to Life. Amy Lee's gothic-rock arena moment."),
    "Evergrey": ("⚔️", "Swedish progressive metal. Recreation Day. Tom Englund's vocal melodrama."),
    "Exodus": ("☣️", "Bay Area thrash. Bonded by Blood. Pre-Metallica Kirk Hammett."),
    "Faith No More": ("\U0001F3AD", "Mike Patton's everything voice. Epic. The Real Thing."),
    "Fall Out Boy": ("⚡", "Sugar We're Goin Down. Pete Wentz's lyrics, Patrick Stump's range. Pop-punk's MTV graduates."),
    "Fatboy Slim": ("\U0001F57A", "Norman Cook. Praise You. Right Here Right Now. Big-beat's biggest face."),
    "Fats Domino": ("\U0001F418", "New Orleans rock-and-roll piano. Blueberry Hill. Original architect."),
    "Fear Factory": ("\U0001F916", "Industrial groove-metal. Demanufacture. Burton C. Bell's scream-melody trade."),
    "Fela Kuti": ("✊", "Afrobeat inventor. Lagos Shrine. Zombie. Thirty wives, one voice, endless hours of groove."),
    "Femi Kuti": ("\U0001F3B7", "Fela's son. Carrying the flame, on his own terms. Africa Shrine."),
    "Foals": ("\U0001F3B8", "Oxford math-rock turned arena indie. Spanish Sahara. Yannis Philippakis's controlled chaos."),
    "Foo Fighters": ("\U0001F941", "Dave Grohl's post-Nirvana redemption. Everlong. The Pretender. Stadium rock's nicest leader."),
    "Foreigner": ("\U0001F494", "I Want to Know What Love Is. Cold as Ice. Lou Gramm's voice, Mick Jones's hooks."),
    "Four Tet": ("\U0001F3B6", "Kieran Hebden. Folktronica architect. Glitchy, organic, contemplative."),
    "Four Tops": ("\U0001F3A4", "Reach Out, I'll Be There. Levi Stubbs's voice. Motown's most consistent quartet."),
    "Frank Sinatra": ("\U0001F3A4", "Ol' Blue Eyes. The Voice. My Way. Fly Me to the Moon. American songbook personified."),
    "Frank Zappa": ("\U0001F468‍\U0001F3A8", "Apostrophe. Hot Rats. Composer disguised as rock star. No genre safe."),
    "Freddie Hubbard": ("\U0001F3BA", "Hard-bop trumpeter. Red Clay. Blue Note's most quoted soloist."),
    "Freddie King": ("\U0001F3B8", "Texas blues bridge. Hide Away. Influenced everyone from Clapton to Stevie Ray."),
    "French Montana": ("\U0001F3A4", "Unforgettable. Bronx by way of Morocco. Bad Boy era's late hits."),
    "Future": ("\U0001F3A7", "Mask Off. Atlanta auto-tune codeine king. Blueprint for a generation."),
    "Gabrielle Aplin": ("\U0001F33A", "Home. The Power of Love. Bristol acoustic-pop."),
    "Gal Costa": ("\U0001F334", "Tropicalia queen. Bahia voice. Caetano's lifelong collaborator."),
    "Gang Starr": ("\U0001F3A4", "Guru and DJ Premier. Moment of Truth. Boom-bap perfection."),
    "Garbage": ("\U0001F339", "Shirley Manson's snarl. Stupid Girl. Butch Vig's grunge-pop Frankenstein."),
    "Garth Brooks": ("\U0001F30E", "Friends in Low Places. The Dance. Country's stadium rocker. Sold more albums than anyone living."),
    "Gary Numan": ("\U0001F916", "Cars. Are 'Friends' Electric? Synth-pop's android godfather."),
    "Genesis": ("\U0001F3AD", "Peter Gabriel's prog years, Phil Collins's pop years. Both eras, both legendary."),
    "George Jones": ("\U0001F942", "He Stopped Loving Her Today. The greatest country singer, full stop. The Possum."),
    "GG Allin": ("\U0001FA78", "Punk's filthiest performer. Self-destruction as art. Died at 36."),
    "Ghostface Killah": ("\U0001F3A4", "Wu-Tang's most vivid storyteller. Supreme Clientele. Bullet-shower flow."),
    "Gigi D’Agostino": ("\U0001F3B5", "L'Amour Toujours. Italian Eurodance pillar. The blue meanie hat."),
    "Gilberto Gil": ("\U0001F3B8", "Tropicalia architect. Brazilian Minister of Culture. Caetano's brother in arms."),
    "Glen Campbell": ("\U0001F3B8", "Wichita Lineman. Rhinestone Cowboy. Wrecking Crew session ace turned star."),
    "Glenn Miller": ("\U0001F3B7", "In the Mood. Pennsylvania 6-5000. Big band era's biggest, lost over the English Channel."),
    "Gloria Estefan": ("\U0001F483", "Conga. Get on Your Feet. Cuban-American Miami sound architect."),
    "Gregory Isaacs": ("\U0001F1EF\U0001F1F2", "Cool Ruler. Night Nurse. Reggae's lover-rocker."),
    "Groove Armada": ("\U0001F3B6", "At the River. UK house-electronic duo's cinematic side."),
    "Guns N’ Roses": ("\U0001F339", "Welcome to the Jungle. Sweet Child o' Mine. Appetite for Destruction. LA hard rock's apex."),
    "Guru": ("\U0001F3A4", "Gang Starr's voice. Jazzmatazz solo. Brooklyn-born baritone."),
    "Hank Snow": ("\U0001F682", "I'm Movin' On. Canadian country pioneer. Got Elvis on the Opry."),
    "Hank Williams": ("\U0001F319", "Your Cheatin' Heart. Lovesick Blues. Country's first poet. Dead at 29."),
    "Hank Williams, Jr.": ("\U0001F30E", "Bocephus. Outlaw country firebrand. Family Tradition."),
    "Harry Belafonte": ("\U0001F334", "Day-O. Calypso went global. Civil rights frontline ally."),
    "Hawkwind": ("\U0001F680", "Silver Machine. Space-rock's longest-running ship. Lemmy's first band."),
    "Heart": ("❤️", "Barracuda. Magic Man. Wilson sisters. Hard rock's most consistent voices."),
    "Horace Andy": ("\U0001F3B6", "Skylarking. Massive Attack collaborator. Reggae falsetto eternal."),
    "Horace Silver": ("\U0001F3B9", "Song for My Father. Hard-bop pianist. Funky modal blueprint."),
    "Hugh Masekela": ("\U0001F3BA", "Grazing in the Grass. South African anti-apartheid voice. Trumpet diplomat."),
    "Hypocrisy": ("\U0001F47A", "Swedish death metal. Peter Tagtgren. UFO obsession."),
    "Iced Earth": ("⚔️", "Florida power-metal. Something Wicked This Way Comes. Jon Schaffer's songwriting."),
    "Iggy Pop": ("\U0001F98E", "Stooges frontman. Lust for Life. The Passenger. Peanut butter and broken glass."),
    "Ike & Tina Turner": ("\U0001F525", "Proud Mary. River Deep, Mountain High. Tina survived Ike, then conquered."),
    "In Flames": ("\U0001F525", "Gothenburg melodic death metal. Colony. Clayman. Anders Friden's evolution."),
    "Infected Mushroom": ("\U0001F344", "Israeli psytrance pioneers. Becoming Insane. Heavy synths, heavier riffs."),
    "INXS": ("\U0001F1E6\U0001F1FA", "Need You Tonight. Australian rock with Michael Hutchence's swagger."),
    "Iron Maiden": ("\U0001F918", "Eddie. Run to the Hills. The Trooper. Steve Harris's gallop. Heavy metal's most theatrical."),
    "Jack White": ("\U0001F3B8", "White Stripes, Raconteurs, Dead Weather. Detroit garage-rock's most prolific obsessive."),
    "James Cotton": ("\U0001F3A4", "Chicago blues harp. Muddy Waters band, then his own. Mississippi by way of Wolf."),
    "James Ingram": ("\U0001F3A4", "Just Once. I Don't Have the Heart. Quincy Jones's go-to ballad voice."),
    "James Last": ("\U0001F3BC", "German bandleader. Easy listening's biggest seller in Europe."),
    "James Moody": ("\U0001F3B7", "Moody's Mood for Love. Bebop tenor saxophonist with vocal-style phrasing."),
    "Jamiroquai": ("\U0001F3A9", "Jay Kay's hat. Virtual Insanity. Acid jazz's most successful export."),
    "Janet Jackson": ("\U0001F48E", "Rhythm Nation. Control. Michael's sister, her own dynasty."),
    "Jean‐Michel Jarre": ("\U0001F30C", "Oxygene. Equinoxe. French electronic music's grand architect."),
    "Jeezy": ("❄️", "Snowman. Atlanta trap pioneer. Trap or Die. The Recession."),
    "Jeff Mills": ("\U0001F39B️", "Detroit techno's most precise. The Wizard. Three turntables, no nonsense."),
    "Jennifer Lopez": ("\U0001F483", "On the 6. Dancer-actress-singer triple threat. Bronx-born brand."),
    "Jerry Lee Lewis": ("\U0001F525", "Great Balls of Fire. Whole Lotta Shakin' Goin' On. The Killer. Piano-pounding rockabilly madman."),
    "Jessie J": ("\U0001F3A4", "Price Tag. Bang Bang. British belt with a bald-head moment."),
    "Jet": ("\U0001F3B8", "Are You Gonna Be My Girl. Australian garage-rock briefly conquered the world."),
    "Jethro Tull": ("\U0001FA88", "Aqualung. Flute-driven prog. Ian Anderson on one leg."),
    "Jim Hall": ("\U0001F3B8", "Concierto. Jazz guitar's quietest virtuoso."),
    "Jimmy Cliff": ("\U0001F1EF\U0001F1F2", "The Harder They Come. Reggae's first global crossover."),
    "Jimmy Eat World": ("\U0001F3B8", "The Middle. Bleed American. Arizona emo-pop's purest hits."),
    "Jimmy Reed": ("\U0001F3B8", "Big Boss Man. Mississippi blues simplified to its essence."),
    "Joanna Newsom": ("\U0001F3BC", "Ys. Harp-driven folk poetry. Lyrics like a literature thesis."),
    "Joe Bonamassa": ("\U0001F3B8", "Modern blues guitar virtuoso. Touring relentlessly."),
    "Joe Henderson": ("\U0001F3B7", "Inner Urge. Hard-bop and modal tenor saxophonist. Lush Life with Wynton Marsalis."),
    "Joe Pass": ("\U0001F3B8", "Solo guitar virtuoso. Virtuoso. Made one guitar sound like a band."),
    "John Farnham": ("\U0001F3A4", "You're the Voice. Australian rock voice. Our anthem-of-the-decade source."),
    "John Lee Hooker": ("\U0001F3B8", "Boom Boom. Boogie Chillen'. Mississippi-to-Detroit blues chant."),
    "John Legend": ("\U0001F3B9", "All of Me. Ordinary People. Soul piano. Husband of Chrissy."),
    "John Lennon": ("☮️", "Imagine. Working Class Hero. Beatles to solo. Shot in 1980."),
    "John Lewis": ("\U0001F3B9", "Modern Jazz Quartet pianist. Third-stream architect."),
    "John Mayall & the Bluesbreakers": ("\U0001F3B8", "British blues finishing school. Clapton, Green, Mick Taylor all graduated."),
    "John Mellencamp": ("\U0001F33D", "Jack & Diane. Pink Houses. Indiana heartland-rock troubadour."),
    "John Zorn": ("\U0001F3B7", "Naked City. Masada. Avant-garde composer. Genre is whatever he says it is."),
    "Johnny Griffin": ("\U0001F3B7", "Little Giant. Bebop tenor with the fastest fingers in the room."),
    "Johnny Mathis": ("\U0001F3A4", "Chances Are. Misty. Pop crooner with the silkiest tenor."),
    "Johnny Winter": ("\U0001F43A", "Texas blues albino virtuoso. Resurrected Muddy Waters in the 70s."),
    "Jonas Brothers": ("\U0001FA90", "Disney's hit-factory siblings. Burnin' Up. Comeback kids."),
    "Jorge Ben Jor": ("\U0001F3B8", "Mas Que Nada. Brazilian samba-rock pillar. Taj Mahal."),
    "José Afonso": ("\U0001F1F5\U0001F1F9", "Grandola, Vila Morena. Portuguese folk that triggered the Carnation Revolution."),
    "José Feliciano": ("\U0001F3B8", "Light My Fire. Feliz Navidad. Puerto Rican guitar virtuoso."),
    "Journey": ("⛰️", "Don't Stop Believin'. Steve Perry's voice. Stadium rock's anthem factory."),
    "João Gilberto": ("\U0001F334", "Bossa nova's whispering father. Chega de Saudade. Stan Getz collaborator."),
    "Judas Priest": ("\U0001F918", "Breaking the Law. Living After Midnight. British metal's leather-and-studs uniform."),
    "Juelz Santana": ("\U0001F3A4", "Dipset's brightest. There It Go. Harlem swagger personified."),
    "Juice WRLD": ("\U0001F327️", "Lucid Dreams. Chicago emo-rap. Gone at 21."),
    "Julee Cruise": ("\U0001F319", "Falling. Twin Peaks's dreamy voice. Angelo Badalamenti and David Lynch's third partner."),
    "Julie London": ("\U0001F339", "Cry Me a River. Smokey jazz vocals. Fifties pin-up to fifties chanteuse."),
    "Julio Iglesias": ("\U0001F339", "Spanish balladeer. Most languages of any pop singer ever. Enrique's father."),
    "June Christy": ("\U0001F3A4", "Something Cool. Stan Kenton vocalist. West Coast cool jazz singer."),
    "Junior Wells": ("\U0001F3A4", "Hoodoo Man Blues. Chicago blues harp and hat."),
    "Junkie XL": ("\U0001F39A️", "Tom Holkenborg. Mad Max: Fury Road score. Dutch electro-orchestral hybrid."),
    "Justin Timberlake": ("\U0001F57A", "Cry Me a River. SexyBack. NSYNC graduate to solo Prince of Pop."),
    "Ye": ("\U0001F441️", "Kanye West. The College Dropout. 808s & Heartbreak. My Beautiful Dark Twisted Fantasy. Genius and chaos."),
    "Kaskade": ("\U0001F305", "Ryan Raddon. Atmosphere. Progressive house's softest hand."),
    "Kataklysm": ("⚔️", "Quebec death metal. Northern hyperblast. Twenty-plus years deep."),
    "Katatonia": ("\U0001F311", "Swedish doom-prog evolved into atmospheric. Brave Murder Day. The Great Cold Distance."),
    "Katy B": ("\U0001F3B6", "On a Mission. UK funky meets pop. Rinse FM royalty."),
    "Keane": ("\U0001F3B9", "Somewhere Only We Know. British piano-rock without a guitar in sight."),
    "Keb’ Mo’": ("\U0001F3B8", "Modern blues troubadour. Acoustic, polished, accessible."),
    "Kelis": ("\U0001F95B", "Milkshake. Caught Out There. Neptunes-era genre-bender."),
    "Ken Carson": ("\U0001F3A4", "Atlanta rage-rap protege. Whole Lotta Red sound carried forward."),
    "Kenny G": ("\U0001F3B7", "Smooth jazz personified. Songbird. Most famous saxophonist alive, by hits."),
    "King Crimson": ("\U0001F441️", "In the Court of the Crimson King. Robert Fripp's prog-rock institution."),
    "King Gizzard & the Lizard Wizard": ("\U0001F98E", "Australian psych-rock prolific maniacs. Different genre every album."),
    "Kings of Leon": ("\U0001F451", "Sex on Fire. Use Somebody. Followill brothers and cousin. Tennessee garage to stadium."),
    "Klaus Schulze": ("\U0001F39B️", "German electronic pioneer. Tangerine Dream alumnus. Berlin school."),
    "Kodak Black": ("\U0001F3A4", "Florida rapper. Roll in Peace. Project Baby. Polarizing voice."),
    "Kool & the Gang": ("\U0001F57A", "Celebration. Get Down on It. Funk-pop dynasty."),
    "Korn": ("\U0001FA78", "Freak on a Leash. Bakersfield nu-metal architects. Jonathan Davis's bagpipes."),
    "Krayzie Bone": ("☘️", "Bone Thugs's most technical. Cleveland harmony rap."),
    "Kreator": ("⚔️", "Pleasure to Kill. German thrash holy trinity third. Mille Petrozza's snarl."),
    "Kris Kristofferson": ("\U0001F942", "Sunday Mornin' Comin' Down. Rhodes scholar turned outlaw country songwriter."),
    "KRS‐One": ("\U0001F3A4", "Boogie Down Productions. The Bridge Wars. Hip-hop's teacher."),
    "Kurupt": ("\U0001F334", "Tha Dogg Pound's ferocity. Snoop's running mate. Long Beach gangsta rap."),
    "Kyuss": ("\U0001F335", "Welcome to Sky Valley. Stoner rock's California desert origin. Pre-QOTSA Josh Homme."),
    "Lana Del Rey": ("\U0001F339", "Video Games. Born to Die. Cinematic Americana melancholy."),
    "Larry Coryell": ("\U0001F3B8", "Jazz-fusion's first guitarist. Spaces."),
    "Lee “Scratch” Perry": ("\U0001F300", "Black Ark studio madness. Reggae producer-prophet. Dub's wild architect."),
    "Less Than Jake": ("\U0001F3BA", "Ska-punk's brassiest. Hello Rockview. Gainesville Florida."),
    "Lester Young": ("\U0001F3B7", "Pres. Tenor saxophone's first cool voice. Billie Holiday's running mate."),
    "Level 42": ("\U0001F3B8", "Lessons in Love. Mark King's slap-bass. British pop-funk."),
    "Liam Gallagher": ("\U0001F98D", "Oasis frontman. Wonderwall's sneer. Pure rockstar attitude."),
    "Lightnin’ Hopkins": ("\U0001F3B8", "Texas blues. Most-recorded bluesman of his era. One-man-band economy."),
    "Lil Uzi Vert": ("\U0001F48E", "XO Tour Llif3. Philadelphia rage-rap. Diamond in the forehead."),
    "Limp Bizkit": ("\U0001F9E2", "Nookie. Rollin'. Fred Durst's red cap. Nu-metal's most polarizing."),
    "Live": ("\U0001F4A1", "Lightning Crashes. York PA alt-rock. Throwing Copper."),
    "LL Cool J": ("\U0001F3A4", "Mama Said Knock You Out. Ladies Love. Queens hip-hop perpetual."),
    "Lloyd Banks": ("\U0001F48E", "G-Unit's Punchline King. Queens lyricist."),
    "Loretta Lynn": ("⛏️", "Coal Miner's Daughter. Country's working-class matriarch."),
    "Lost Frequencies": ("\U0001F305", "Are You with Me. Belgian deep house's biggest export."),
    "Lou Donaldson": ("\U0001F3B7", "Alligator Bogaloo. Hard-bop alto with a soul-jazz pivot."),
    "Louis Armstrong": ("\U0001F3BA", "Satchmo. What a Wonderful World. The trumpet that invented the solo."),
    "Luiz Bonfá": ("\U0001F3B8", "Manha de Carnaval. Brazilian guitarist. Black Orpheus soundtrack."),
    "Lynn Anderson": ("\U0001F339", "Rose Garden. Crossover country gold."),
    "Lynyrd Skynyrd": ("\U0001F985", "Sweet Home Alabama. Free Bird. Southern rock icons. The plane crash that ended everything."),
    "Mac Miller": ("☁️", "Swimming. Self Care. Pittsburgh emotional honesty. Gone at 26."),
    "Machine Head": ("⚙️", "Burn My Eyes. Bay Area groove-metal. Robb Flynn's growl."),
    "Macy Gray": ("\U0001F3A4", "I Try. Husky-voiced soul singer. That voice nobody else has."),
    "Madlib": ("\U0001F39B️", "Otis Jackson Jr. Beat conductor. Madvillainy with MF DOOM. Quasimoto alter ego."),
    "Madness": ("\U0001F3A9", "One Step Beyond. Our House. London ska's nutty boys."),
    "Mahalia Jackson": ("\U0001F64F", "Gospel queen. How I Got Over. The voice that moved Dr. King."),
    "Manfred Mann": ("\U0001F3B9", "Do Wah Diddy Diddy. South African keyboardist's British invasion band, then Earth Band."),
    "Manic Street Preachers": ("\U0001F339", "A Design for Life. Welsh art-rock with politics on the sleeve."),
    "Manu Dibango": ("\U0001F3B7", "Soul Makossa. Cameroonian sax that sampled itself into Michael Jackson."),
    "Marduk": ("⚔️", "Swedish black metal. Panzer Division Marduk. Relentless blast-beat extremity."),
    "Marillion": ("\U0001F3BC", "Misplaced Childhood. British neo-prog. Fish-era to Steve Hogarth."),
    "Marilyn Manson": ("\U0001F40D", "Antichrist Superstar. Brian Warner's shock-rock theater."),
    "Mark Isham": ("\U0001F3BA", "Trumpeter turned film composer. A River Runs Through It. Quietly prolific."),
    "Markus Schulz": ("\U0001F30D", "Coldharbour Recordings. Trance DJ's most consistent name."),
    "Martha Reeves and the Vandellas": ("\U0001F483", "Dancing in the Street. Heat Wave. Motown's Detroit-sound trio."),
    "Martin Solveig": ("\U0001F3A9", "Hello. Intoxicated. French house-pop crossover."),
    "Max Roach": ("\U0001F941", "Bebop drummer. We Insist! Drums as composition."),
    "Mayhem": ("☠️", "De Mysteriis Dom Sathanas. Norwegian black metal's church-burning origin myth."),
    "MC Eiht": ("\U0001F3A4", "Compton's Most Wanted. Gangsta storyteller. Geah."),
    "MC Solaar": ("\U0001F3A4", "Caroline. French rap's literary godfather. Senegalese-Parisian flow."),
    "McCoy Tyner": ("\U0001F3B9", "Coltrane's quartet pianist. The Real McCoy. Modal jazz's pillar."),
    "Megadeth": ("\U0001F918", "Rust in Peace. Dave Mustaine's revenge after Metallica. Thrash technicality."),
    "Melvins": ("\U0001F40C", "Houdini. Buzz Osborne's Aberdeen sludge. Pre-Nirvana, post-everything."),
    "Memphis Minnie": ("\U0001F3B8", "Country blues woman who cut sides into the 50s. Hoodoo Lady."),
    "Memphis Slim": ("\U0001F3B9", "Mother Earth. Boogie-woogie pianist. Chicago to Paris exile."),
    "Merle Haggard": ("\U0001F682", "Mama Tried. Okie from Muskogee. Country's working-class poet laureate."),
    "Metallica": ("\U0001F918", "Master of Puppets. Enter Sandman. Bay Area thrash that became the biggest metal band ever."),
    "MF DOOM": ("\U0001F3AD", "Daniel Dumile. Mask. Madvillainy. Operation: Doomsday. Hip-hop's supervillain."),
    "Michel Legrand": ("\U0001F3BC", "French composer. The Umbrellas of Cherbourg. Jazz harmonist for film."),
    "Mick Taylor": ("\U0001F3B8", "Stones's second guitarist. Sticky Fingers, Exile on Main St. The blues injection."),
    "Migos": ("\U0001F48E", "Atlanta trap trio. Bad and Boujee. Triplet flow's blueprint. Takeoff gone too soon."),
    "Mike Oldfield": ("\U0001F514", "Tubular Bells. The Exorcist theme. Multi-instrumentalist's first-album empire."),
    "Milt Jackson": ("\U0001F3B5", "Vibraphone bebopper. Modern Jazz Quartet's lyrical engine."),
    "Miriam Makeba": ("\U0001F1FF\U0001F1E6", "Mama Africa. Pata Pata. South African voice exiled by apartheid."),
    "Mobb Deep": ("\U0001F3A4", "Shook Ones Pt. II. Queensbridge nightmare-rap. Prodigy and Havoc's chemistry."),
    "Moby": ("\U0001F4BF", "Play. Everything Is Wrong. Vegan electronic sample sourcerer."),
    "Modest Mouse": ("\U0001F690", "Float On. Issaquah indie's biggest moment. Isaac Brock's yelp."),
    "Mogwai": ("\U0001F32B️", "Glasgow post-rock. Young Team. Loud and quiet are their language."),
    "Moloko": ("\U0001F3B6", "Sing It Back. The Time Is Now. Roisin Murphy and Mark Brydon. Trip-pop."),
    "Mongo Santamaría": ("\U0001F941", "Watermelon Man. Cuban conga-jazz pillar. Took Herbie Hancock's tune and made it his."),
    "Moonspell": ("\U0001F43A", "Portuguese gothic metal. Wolfheart. Fernando Ribeiro's snarl."),
    "Morbid Angel": ("\U0001F47A", "Florida death metal architects. Altars of Madness. Trey Azagthoth."),
    "Morrissey": ("\U0001F339", "Smiths frontman, then solo monument. Suedehead. Provocateur and poet."),
    "Motörhead": ("\U0001F918", "Ace of Spades. Lemmy's bass-rasp gospel. Three chords played louder than yours."),
    "MUCC": ("\U0001F3B8", "Visual kei rock. Japanese alt-metal across two decades."),
    "My Dying Bride": ("\U0001F319", "UK doom-death original. As the Flower Withers. Aaron Stainthorpe's grief poetry."),
    "Mötley Crüe": ("\U0001F48B", "Shout at the Devil. Dr. Feelgood. Sunset Strip glam-metal sleaze."),
    "Nana Mouskouri": ("\U0001F339", "Greek voice. Glasses. 350 million records sold across decades."),
    "Napalm Death": ("☠️", "You Suffer (one second). Birmingham grindcore architects."),
    "Narada Michael Walden": ("\U0001F941", "Drummer turned hit producer. Whitney Houston, Aretha, Mariah."),
    "Nat King Cole": ("\U0001F3B9", "Unforgettable. Smile. Pianist who sang too. Gentle pop perfection."),
    "Natalie Cole": ("\U0001F339", "Unforgettable duet with her father. R&B torch."),
    "New Found Glory": ("\U0001F3B8", "My Friends Over You. Florida pop-punk consistency."),
    "Nick Cave & the Bad Seeds": ("\U0001FAA6", "Into My Arms. Murder ballads. Australian gothic-rock priest."),
    "Nightwish": ("⚔️", "Finnish symphonic metal. Tarja Turunen's operatic peak. Tuomas Holopainen's vision."),
    "Nine Inch Nails": ("\U0001F529", "Closer. Hurt. Trent Reznor's industrial-rock empire."),
    "Noisia": ("\U0001F39B️", "Dutch drum-and-bass precision. Twenty years of low-end engineering."),
    "Nokturnal Mortum": ("\U0001F312", "Ukrainian black metal. Folk-pagan undercurrent."),
    "Norah Jones": ("\U0001F3B9", "Don't Know Why. Come Away with Me. Diana Krall's cooler sister act."),
    "Obituary": ("\U0001FAA6", "Florida death metal. Slowly We Rot. John Tardy's grunt."),
    "Opeth": ("\U0001F332", "Blackwater Park. Swedish prog-death. Mikael Akerfeldt's growl-to-clean dance."),
    "Orbital": ("\U0001F311", "Halcyon. Hartnoll brothers' UK techno-rave architecture."),
    "Oscar Peterson": ("\U0001F3B9", "Night Train. Canadian piano virtuoso. Filled every space, expertly."),
    "Otis Rush": ("\U0001F3B8", "Chicago blues lefty. I Can't Quit You Baby. The west side school."),
    "Outlawz": ("\U0001F3A4", "Tupac's group. Hit 'Em Up affiliates. Death Row affiliates."),
    "Overkill": ("\U0001F9B4", "New Jersey thrash. Bobby Blitz Ellsworth's screech."),
    "O‐Zone": ("\U0001F1F2\U0001F1E9", "Dragostea Din Tei. The Numa Numa song. Romanian-Moldovan one-hit phenomenon."),
    "Paco de Lucía": ("\U0001F1EA\U0001F1F8", "Spanish flamenco guitar revolution. Entre Dos Aguas. Camaron's lifelong partner."),
    "Pain of Salvation": ("\U0001F300", "Daniel Gildenlow. Swedish prog-metal at its most emotional."),
    "Paloma Faith": ("\U0001F380", "Stone Cold Sober. British retro-soul with vintage everything."),
    "Pantera": ("\U0001F918", "Vulgar Display of Power. Cowboys from Hell. Dimebag's groove-metal blueprint."),
    "Paquito D’Rivera": ("\U0001F3B7", "Cuban-American sax. Irakere alumnus. Latin jazz at its most virtuosic."),
    "Paradise Lost": ("\U0001F987", "UK gothic-doom architects. Gothic. The genre's first manifesto."),
    "Paramore": ("\U0001F9E1", "Misery Business. Hayley Williams's voice. Tennessee pop-punk's biggest export."),
    "Paul Bley": ("\U0001F3B9", "Canadian free-jazz pianist. Open, Spaces. Carla Bley's first marriage."),
    "Paul Desmond": ("\U0001F3B7", "Take Five composer. Dave Brubeck Quartet alto. The dry martini sound."),
    "Paul Oakenfold": ("\U0001F3A7", "Bunkka. UK trance pioneer. Goa to Ibiza to Vegas."),
    "Paul Simon": ("\U0001F3B8", "Graceland. The Sound of Silence. Garfunkel's other half, then solo monument."),
    "Paul van Dyk": ("\U0001F39B️", "For an Angel. Berlin trance's most precise."),
    "Paul Weller": ("\U0001F1EC\U0001F1E7", "The Jam, then Style Council, then Modfather solo. British rock conscience."),
    "Peggy Lee": ("\U0001F339", "Fever. Is That All There Is. Cool jazz vocals. Disney's Lady and the Tramp."),
    "Percy Sledge": ("\U0001F494", "When a Man Loves a Woman. Alabama soul that crystallized a feeling."),
    "Perfume": ("\U0001F3A4", "Japanese electropop trio. Yasutaka Nakata's vocoder factory."),
    "Perry Como": ("\U0001F3A4", "Catch a Falling Star. Italian-American crooner. The relaxed sweater era."),
    "Peter Gabriel": ("\U0001F441️", "Genesis frontman, then solo monument. In Your Eyes. Sledgehammer."),
    "Pharoah Sanders": ("\U0001F3B7", "Coltrane's spiritual heir. The Creator Has a Master Plan."),
    "Philip Glass": ("\U0001F3BC", "Minimalist composer. Glassworks. Einstein on the Beach. The arpeggio empire."),
    "Phish": ("\U0001F41F", "Vermont jam pioneers. Trey Anastasio's noodle empire. Dead heirs."),
    "Porcupine Tree": ("\U0001F332", "Steven Wilson's prog vehicle. In Absentia. Modern prog's revival point."),
    "Portugal. The Man": ("\U0001F6AA", "Feel It Still. Alaska indie that turned arena-pop."),
    "Public Image Ltd": ("\U0001F399️", "Lydon post-Sex Pistols. Metal Box. Post-punk's manifesto."),
    "Queens of the Stone Age": ("\U0001F451", "Songs for the Deaf. No One Knows. Josh Homme's desert-rock authority."),
    "Queensrÿche": ("⚔️", "Operation: Mindcrime. Geoff Tate's prog-metal opus."),
    "R. Kelly": ("⛓️", "I Believe I Can Fly. Then everything else. Talent and crime, intertwined."),
    "R.L. Burnside": ("\U0001F3B8", "North Mississippi hill country blues. Junior Kimbrough's neighbor."),
    "Rage": ("⚔️", "German power-metal trio. Peavy Wagner."),
    "Rage Against the Machine": ("✊", "Killing in the Name. Tom Morello's effects-pedal radicalism."),
    "Ralph Stanley": ("\U0001FA95", "O Brother soundtrack catalyst. Bluegrass mountain voice."),
    "Randy Crawford": ("\U0001F3A4", "Street Life with Crusaders. R&B chanteuse."),
    "Randy Weston": ("\U0001F3B9", "African Cookbook. Pan-African jazz pianist."),
    "Ray Charles": ("\U0001F576️", "Georgia on My Mind. What'd I Say. Soul music's architect."),
    "REO Speedwagon": ("\U0001F690", "Can't Fight This Feeling. Illinois arena rock's earnest one."),
    "Riverside": ("\U0001F30A", "Polish prog rock. Mariusz Duda's atmospheric melancholy."),
    "Robert Johnson": ("\U0001F47B", "Crossroads myth. Sweet Home Chicago. Twenty-nine recordings, then dead at 27."),
    "Robin Schulz": ("\U0001F39B️", "Sugar. Prayer in C remix. German tropical house's quiet titan."),
    "Rod Stewart": ("\U0001F942", "Maggie May. Da Ya Think I'm Sexy. Sandpaper voice across genres."),
    "Roger Whittaker": ("\U0001F3A4", "Durham Town. The Last Farewell. Whistling baritone."),
    "Rotting Christ": ("\U0001F1EC\U0001F1F7", "Greek black metal. Theogonia. Sakis Tolis's ancient-paganism turn."),
    "Roy Ayers": ("\U0001FA84", "Everybody Loves the Sunshine. Vibraphone funk. Jazz-funk crossover ambassador."),
    "Roy Buchanan": ("\U0001F3B8", "The world's best unknown guitarist. Telecaster wizard."),
    "Rubén Blades": ("\U0001F3A4", "Pedro Navaja. Panamanian salsa storyteller. Lawyer too."),
    "Run‐D.M.C.": ("\U0001F45F", "Walk This Way. Adidas. Queens hip-hop's first crossover."),
    "Rush": ("\U0001F3B8", "Tom Sawyer. YYZ. Geddy, Alex, Neil. Canada's most precise prog trio."),
    "RZA": ("\U0001F3A4", "Wu-Tang's architect. Producer-rapper-Shaolin theorist."),
    "Sade": ("\U0001F339", "Smooth Operator. No Ordinary Love. Helen Folasade Adu's sophisticated cool."),
    "Saint Etienne": ("\U0001F3B6", "Foxbase Alpha. Bob Stanley's UK indie-pop archive made into music."),
    "Salt‐N‐Pepa": ("\U0001F48B", "Push It. Whatta Man. Queens hip-hop's first female superstars."),
    "Sam & Dave": ("\U0001F3A4", "Soul Man. Hold On, I'm Comin'. Stax double act."),
    "Santana": ("\U0001F33A", "Black Magic Woman. Carlos's Latin-rock guitar. Woodstock to Supernatural."),
    "Sash!": ("\U0001F30D", "Encore une Fois. Adelante. German Eurodance ubiquity."),
    "Savatage": ("\U0001F3BB", "Gutter Ballet. Florida prog-metal. Trans-Siberian Orchestra's seed."),
    "Scooter": ("\U0001F4E2", "H.P. Baxxter's How Much Is the Fish? German happy-hardcore loud."),
    "Scorpions": ("\U0001F982", "Wind of Change. Rock You Like a Hurricane. Hannover hard rock with the most German anthem ever."),
    "Seal": ("\U0001F339", "Kiss from a Rose. Crazy. Trevor Horn-produced soul-pop royalty."),
    "Sepultura": ("\U0001F1E7\U0001F1F7", "Roots. Brazilian thrash going tribal. Cavalera brothers' apex."),
    "Sevendust": ("\U0001F918", "Atlanta nu-metal. Lajon Witherspoon's voice."),
    "Shania Twain": ("\U0001F483", "Man! I Feel Like a Woman. Country-pop crossover queen. Mutt Lange's rock production."),
    "Sheryl Crow": ("\U0001F3B8", "All I Wanna Do. If It Makes You Happy. Tuesday Night Music Club, every Tuesday since."),
    "SHINee": ("\U0001F48E", "K-pop boy band royalty. Lucifer. Ring Ding Dong. Jonghyun's loss."),
    "Sia": ("\U0001F3A4", "Chandelier. Australian voice behind countless hits, then a face-hiding wig."),
    "Sigur Rós": ("\U0001F30C", "Icelandic post-rock. Hopelandic invented language. Glaciers turned into albums."),
    "Simple Plan": ("\U0001F3B8", "Quebec pop-punk. I'd Do Anything. Welcome to My Life."),
    "Sizzla": ("\U0001F1EF\U0001F1F2", "Bobo Ashanti dancehall. Solid as a Rock. Conscious lyrics over rough rhythm."),
    "Skeeter Davis": ("\U0001F327️", "The End of the World. Country crossover sweetness."),
    "Skip James": ("\U0001F3B8", "Devil Got My Woman. Falsetto Delta blues. Cypress Grove."),
    "Slayer": ("\U0001FA78", "Reign in Blood. Raining Blood. Thrash's most uncompromising. Tom Araya's scream."),
    "Slipknot": ("\U0001F3AD", "Iowa. Nine masks. Joey Jordison. Corey Taylor's dual life."),
    "Snow Patrol": ("⭐", "Chasing Cars. Northern Irish soft-rock arena moment."),
    "Sodom": ("⚔️", "German thrash trinity third with Kreator and Destruction. Agent Orange."),
    "Soilwork": ("⚒️", "Helsingborg melodic death. Swedish craft."),
    "Son House": ("\U0001FA95", "Death Letter. Mississippi Delta blues. Slide-guitar prophet rediscovered in the 60s."),
    "Sonic Youth": ("\U0001F3B8", "Daydream Nation. New York noise-rock institution. Thurston, Kim, Lee, Steve."),
    "Sonny Boy Williamson": ("\U0001F3A4", "Two players took the name. The second's harmonica defined Chicago blues."),
    "Sonny Rollins": ("\U0001F3B7", "Saxophone Colossus. The bridge sabbatical. Tenor sax's most singing voice."),
    "Soulfly": ("\U0001F40D", "Max Cavalera post-Sepultura. Tribal metal continues."),
    "Spiritualized": ("\U0001F680", "Ladies and Gentlemen We Are Floating in Space. Jason Pierce's gospel-noise."),
    "Stan Kenton": ("\U0001F3BA", "Big band leader. Progressive jazz architect. Artistry in Rhythm."),
    "Status Quo": ("\U0001F3B8", "Rockin' All Over the World. UK's denim-and-boogie working man's band."),
    "Stereolab": ("\U0001F39B️", "Cobra and Phases. French-British krautpop dreamers."),
    "Stereophonics": ("\U0001F3B8", "Welsh rock trio. Dakota. Kelly Jones's rasp."),
    "Sting": ("\U0001F3B8", "Police frontman, then solo. Roxanne. Englishman in New York. Tantric reputation."),
    "Styx": ("\U0001F6A2", "Come Sail Away. Renegade. Chicago prog-pomp."),
    "Sublime": ("☀️", "Long Beach ska-punk. Bradley Nowell's voice. Heroin took him at 28."),
    "Suede": ("\U0001F339", "Britpop's androgynous start. Brett Anderson and Bernard Butler's tension."),
    "Suzanne Vega": ("\U0001F3B8", "Tom's Diner. Luka. NYC folk that DNA-tested the MP3."),
    "Swans": ("⚫", "Michael Gira's American gothic. Sounds heavier than metal without metal's tools."),
    "System of a Down": ("\U0001F1E6\U0001F1F2", "Toxicity. Chop Suey. Armenian-American polemic-metal."),
    "Taj Mahal": ("\U0001F30D", "Multi-instrumental world-blues ambassador. Caribbean to Mali."),
    "Taking Back Sunday": ("\U0001F494", "Tell All Your Friends. Long Island emo's apex."),
    "Tamia": ("\U0001F3A4", "Officially Missing You. Canadian R&B with the warmest voice."),
    "Tammi Terrell": ("\U0001F3A4", "Marvin Gaye duet partner. Ain't No Mountain. Gone at 24."),
    "Tankard": ("\U0001F37A", "German thrash's beer-soaked humor. The Morning After."),
    "Tanya Tucker": ("\U0001F920", "Delta Dawn. Country since age 13. Outlaw forever."),
    "Teddy Pendergrass": ("\U0001F3A4", "If You Don't Know Me by Now. Philadelphia soul's most masculine baritone."),
    "Teddy Wilson": ("\U0001F3B9", "Swing pianist. Benny Goodman's quartet. Billie Holiday's foil."),
    "Ten Years After": ("\U0001F3B8", "Goin' Home at Woodstock. Alvin Lee's blues-rock speed."),
    "Tennessee Ernie Ford": ("\U0001F920", "Sixteen Tons. Country-gospel-pop crossover before Garth."),
    "Testament": ("⚔️", "Bay Area thrash that came after. Practice What You Preach. Chuck Billy's bellow."),
    "The Animals": ("\U0001F43A", "House of the Rising Sun. Newcastle British invasion's grit."),
    "The Band": ("\U0001F3B8", "The Weight. Music from Big Pink. Robbie Robertson's Canadian-Americana."),
    "The Black Keys": ("⚫", "Akron blues-rock duo. Brothers. Lonely Boy. Two became huge."),
    "The Brian Jonestown Massacre": ("\U0001F48A", "Anton Newcombe's chaos. Dig! made the legend."),
    "The Cranberries": ("\U0001F1EE\U0001F1EA", "Linger. Zombie. Dolores O'Riordan's voice. Lost in 2018."),
    "The Decemberists": ("⚓", "Colin Meloy's sea shanties. Picaresque storytelling indie."),
    "The Dubliners": ("\U0001F37B", "Whiskey in the Jar. Irish folk's bearded standard-bearers."),
    "The E Street Band": ("\U0001F1FA\U0001F1F8", "Bruce's band. Clarence Clemons's sax. Max Weinberg's drums. Heart of Jersey rock."),
    "The Fall": ("\U0001F4FA", "Mark E. Smith's 40-year complaint. UK post-punk's most prolific iconoclast."),
    "The Flaming Lips": ("\U0001F388", "Soft Bulletin. Yoshimi. Wayne Coyne's psych-pop circus."),
    "The Four Seasons": ("\U0001F3A4", "Sherry. Big Girls Don't Cry. Frankie Valli's falsetto, Jersey-born."),
    "The Game": ("\U0001F334", "Compton rapper. Dr. Dre's protege. The Documentary album."),
    "The Gathering": ("\U0001F319", "Dutch atmospheric rock. Anneke van Giersbergen's voice."),
    "The Highwaymen": ("\U0001F920", "Cash, Nelson, Kristofferson, Jennings. Outlaw country's superstar gang."),
    "The Jesus and Mary Chain": ("\U0001F32B️", "Psychocandy. Reid brothers' feedback-pop. Shoegaze's seed."),
    "The Kinks": ("\U0001F3B8", "You Really Got Me. Waterloo Sunset. Ray Davies's Englishness."),
    "The Manhattan Transfer": ("\U0001F399️", "Vocal jazz quartet. Birdland. Operator."),
    "The Miracles": ("\U0001F3A4", "Smokey Robinson's Motown vehicle. Tracks of My Tears."),
    "The Modern Jazz Quartet": ("\U0001F3B5", "MJQ. John Lewis. Milt Jackson. Chamber-jazz refinement."),
    "The Moody Blues": ("\U0001F30C", "Nights in White Satin. Days of Future Passed. Symphonic prog pioneers."),
    "The Orb": ("\U0001F30D", "Little Fluffy Clouds. Adventures Beyond the Ultraworld. UK ambient-house architects."),
    "The Platters": ("\U0001F3B5", "Only You. Smoke Gets in Your Eyes. Doo-wop's biggest sellers."),
    "The Police": ("\U0001F693", "Roxanne. Every Breath You Take. Sting, Stewart, Andy. Reggae-punk perfection."),
    "The Psychedelic Furs": ("\U0001F339", "Pretty in Pink. Richard Butler's smoke-roughened voice. UK new wave."),
    "The Roots": ("\U0001F941", "Things Fall Apart. Black Thought's flow. Hip-hop's only true band, plus Tonight Show gig."),
    "The Shadows": ("\U0001F3B8", "Apache. UK instrumental rock's first guitar heroes. Cliff Richard's band."),
    "The Skatalites": ("\U0001F1EF\U0001F1F2", "Jamaican ska originators. Studio One house band."),
    "The Smashing Pumpkins": ("\U0001F383", "Mellon Collie. 1979. Billy Corgan's doomed grand vision."),
    "The Spencer Davis Group": ("\U0001F3B9", "Gimme Some Lovin'. Steve Winwood was 17. UK R&B precision."),
    "The Stranglers": ("\U0001F990", "Golden Brown. UK punk-pop with keyboard hooks."),
    "The Sugarhill Gang": ("\U0001F3A4", "Rapper's Delight. Hip-hop's first crossover smash."),
    "The Velvet Underground": ("\U0001F34C", "Andy Warhol's banana. Lou Reed and John Cale. Heroin. Avant-rock's birth."),
    "The Ventures": ("\U0001F30A", "Walk Don't Run. Surf instrumental rock's biggest globally."),
    "The Yardbirds": ("\U0001F3B8", "For Your Love. Three Clapton-Beck-Page guitarists, in a row. Britain's blues-rock bridge."),
    "Theatre of Tragedy": ("\U0001F987", "Norwegian gothic-doom. Aegis. Beauty-and-beast vocal trade."),
    "Thelonious Monk": ("\U0001F3A9", "Round Midnight. Straight, No Chaser. Jazz piano's most singular voice."),
    "Tina Turner": ("\U0001F525", "What's Love Got to Do with It. Proud Mary. Survived Ike, then ruled rock."),
    "Tiësto": ("\U0001F3A7", "Adagio for Strings. Dutch trance turned EDM mainstream."),
    "Tokio Hotel": ("\U0001F1E9\U0001F1EA", "German teen-pop-rock. Bill Kaulitz's androgynous icon turn."),
    "Tom Waits": ("\U0001F942", "Rain Dogs. Closing Time. Gravelly voice that became a junkyard symphony."),
    "Tommy Flanagan": ("\U0001F3B9", "Bebop pianist. Coltrane's Giant Steps backing. Ella's regular accompanist."),
    "Toni Braxton": ("\U0001F3A4", "Un-Break My Heart. R&B contralto. Babyface's muse."),
    "Tony Allen": ("\U0001F941", "Fela's drummer. Afrobeat's foundational rhythm."),
    "Tony Bennett": ("\U0001F3A4", "I Left My Heart in San Francisco. Crooner who never stopped, until 96."),
    "Toots & The Maytals": ("\U0001F1EF\U0001F1F2", "Pressure Drop. Fred Toots Hibbert's ska-reggae voice."),
    "Tori Amos": ("\U0001F3B9", "Cornflake Girl. Crucify. Boys for Pele. Piano confessions."),
    "Toto": ("\U0001F327️", "Africa. Rosanna. LA studio aces who became their own band."),
    "Troye Sivan": ("\U0001F308", "Australian pop. Bloom. Indie pop with a quiet swagger."),
    "Type O Negative": ("\U0001F377", "Black No. 1. Peter Steele's basso. Brooklyn gothic-doom."),
    "T‐Bone Walker": ("\U0001F3B8", "Stormy Monday. Texas blues-jazz electric guitar pioneer."),
    "U2": ("\U0001F1EE\U0001F1EA", "One. Where the Streets Have No Name. Bono and the Edge's Dublin-to-stadium arc."),
    "U96": ("\U0001F30D", "Das Boot. German techno-trance pioneers."),
    "UB40": ("\U0001F1EC\U0001F1E7", "Red Red Wine. Birmingham reggae crossover."),
    "Udo Lindenberg": ("\U0001F1E9\U0001F1EA", "German rock institution. Sonderzug nach Pankow. Hat-and-shades icon."),
    "Underworld": ("\U0001F39B️", "Born Slippy. Trainspotting's anthem. UK techno-rock duo."),
    "Uriah Heep": ("⚔️", "Easy Livin'. UK proto-metal hard rock. David Byron's voice."),
    "UVERworld": ("\U0001F1EF\U0001F1F5", "Japanese rock with a saxophone in the band. Anime opening regulars."),
    "Vader": ("⚔️", "Polish death metal architects. The Ultimate Incantation. Peter's intensity."),
    "Van Morrison": ("\U0001F312", "Astral Weeks. Brown Eyed Girl. Belfast Cowboy. Eternal mystic."),
    "Venom": ("\U0001F47F", "Welcome to Hell. Black Metal. UK proto-extreme metal that named the genres."),
    "Vince Staples": ("\U0001F334", "Long Beach rapper. Summertime '06. Deadpan storytelling."),
    "Voivod": ("\U0001F47D", "Quebec sci-fi thrash. Killing Technology. Piggy's Voivod chord."),
    "Wayne Shorter": ("\U0001F3B7", "Footprints. Jazz Messengers, then Miles, then Weather Report. Saxophonist as shaman."),
    "Ween": ("\U0001F3AD", "Brown's drug. Pure Guava. Pennsylvania weirdo brothers in name only."),
    "Weezer": ("\U0001F7E6", "Buddy Holly. Say It Ain't So. Rivers Cuomo's sweater-rock confessional."),
    "Wes Montgomery": ("\U0001F3B8", "Octaves. Smokin' at the Half Note. Indianapolis jazz guitar's thumb-driven king."),
    "Wilson Pickett": ("\U0001F3A4", "In the Midnight Hour. Land of 1000 Dances. Stax soul shouter."),
    "Xasthur": ("\U0001F987", "California depressive black metal. Malefic's bedroom solo project."),
    "XTC": ("\U0001F3B8", "Making Plans for Nigel. Andy Partridge's Swindon power-pop wit."),
    "Yello": ("\U0001F39B️", "Oh Yeah (Ferris Bueller). Swiss electronic eccentrics."),
    "Yellow Magic Orchestra": ("\U0001F1EF\U0001F1F5", "Sakamoto, Hosono, Takahashi. Tokyo synth-pop architects."),
    "Yes": ("\U0001F30C", "Roundabout. Owner of a Lonely Heart. Prog rock's longest-running ship."),
    "Yo La Tengo": ("\U0001F3B5", "Hoboken indie veterans. Painful. And Then Nothing Turned Itself Inside-Out."),
    "YoungBoy Never Broke Again": ("\U0001F3A4", "Baton Rouge prolific rapper. Streaming-era hit machine."),
    "אריק איינשטיין": ("\U0001F1EE\U0001F1F1", "Israeli rock founder. Sa Le'at. The voice of a generation."),
    "中森明菜": ("\U0001F1EF\U0001F1F5", "Showa pop queen. Shoujo A. Seiko's eternal rival."),
    "倉木麻衣": ("\U0001F3A4", "Japanese pop. Stay by My Side. Detective Conan's theme voice."),
    "倖田來未": ("\U0001F48B", "Japanese R&B-pop. Kyoto-born siren."),
    "坂本龍一": ("\U0001F3B9", "Merry Christmas Mr. Lawrence. YMO. Last Emperor score. Composer-philosopher."),
    "安室奈美恵": ("\U0001F483", "J-pop empress. Okinawa to global. Can You Celebrate."),
    "浜崎あゆみ": ("\U0001F451", "Heisei pop empress. Avex Trax's biggest-ever artist."),
    "王菲": ("\U0001F3A4", "Chungking Express. Mandopop icon. Cocteau Twins's Chinese sister."),
    "Måneskin": ("\U0001F3B8", "Italian rock revival. Beggin'. Eurovision 2021 winners turned global."),
    "N.W.A": ("\U0001F3A4", "Compton. Straight Outta. Eazy, Dre, Cube, MC Ren, DJ Yella. Gangsta rap's seismic event."),
    "NewJeans": ("\U0001F456", "K-pop's 2022 phenomenon. Hype Boy. Min Hee-jin's clean-aesthetic project."),
    "Röyksopp": ("\U0001F3B6", "Eple. Norwegian electronic duo. Melody A.M. atmosphere."),
    "Anitta": ("\U0001F1E7\U0001F1F7", "Brazilian funk-pop. Envolver. Rio's biggest export to global pop."),
    "Jessie Ware": ("\U0001F3A4", "Devotion. Spotlight. UK alt-R&B with disco rebirth."),
    "M.I.A.": ("⚡", "Paper Planes. Sri Lankan-British genre-collisionist. Politics with a beat."),
    "Skindred": ("\U0001F1EC\U0001F1E7", "Welsh ragga-metal. Nobody. Benji Webbe's reggae-punk fusion."),
}

with CSV_PATH.open("r", encoding="utf-8-sig", newline="") as f:
    rows = list(csv.reader(f))

header = rows[0]
ni = header.index("name")
ii = header.index("icon")
di = header.index("description")
ci = header.index("confirmed")

updated = 0
missing = []
for name, (icon, desc) in UPDATES.items():
    found = False
    for row in rows[1:]:
        if row[ni] == name:
            row[ii] = icon
            row[di] = desc
            row[ci] = "yes"
            updated += 1
            found = True
            break
    if not found:
        missing.append(name)

buf = io.StringIO()
csv.writer(buf, lineterminator="\r\n").writerows(rows)
CSV_PATH.write_bytes(b"\xef\xbb\xbf" + buf.getvalue().encode("utf-8"))

print(f"Updated {updated} of {len(UPDATES)} prepared rows")
if missing:
    print(f"MISSING: {missing}")
