# Refresh USDA coffee harvest data.
# Output: src/data/coffee-usda.js  (auto-generated, do not hand-edit)
#
# The composed multi-source dataset lives in src/data/coffee-harvest.js,
# which imports from coffee-usda.js and layers hand-maintained overlays
# (Conab, FNC, Vietnam Customs, etc.) + editorial event annotations on top.
#
# Run from anywhere; script resolves its own directory.
# Intended to be run periodically (monthly) to pick up USDA revisions.
# Backend team (guapa-data) will eventually run this on a schedule.

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir '..\..')
$workDir = Join-Path $scriptDir '.work'
$zipPath = Join-Path $workDir 'psd_coffee_csv.zip'
$csvPath = Join-Path $workDir 'psd_coffee.csv'
$jsonPath = Join-Path $workDir 'harvest-by-country.json'
$outPath = Join-Path $repoRoot 'src\data\coffee-usda.js'

New-Item -ItemType Directory -Force -Path $workDir | Out-Null

Write-Host "[1/3] Fetching USDA PSD coffee dataset..."
Invoke-WebRequest -Uri 'https://apps.fas.usda.gov/psdonline/downloads/psd_coffee_csv.zip' -OutFile $zipPath -UseBasicParsing
Expand-Archive -Path $zipPath -DestinationPath $workDir -Force

Write-Host "[2/3] Aggregating country x year production (attr 028)..."
$rows = Import-Csv $csvPath | Where-Object { $_.Attribute_ID -eq '028' }

$byCountryYear = @{}
foreach ($r in $rows) {
    $c = $r.Country_Name
    $y = [int]$r.Market_Year
    $m = [int]$r.Month
    $v = [double]$r.Value
    $key = "$c|$y"
    if (-not $byCountryYear.ContainsKey($key) -or $byCountryYear[$key].Month -lt $m) {
        $byCountryYear[$key] = @{ Country = $c; Year = $y; Month = $m; Value = $v }
    }
}

$byCountry = @{}
foreach ($rec in $byCountryYear.Values) {
    if (-not $byCountry.ContainsKey($rec.Country)) { $byCountry[$rec.Country] = @{} }
    $byCountry[$rec.Country][$rec.Year.ToString()] = [math]::Round($rec.Value / 1000, 2)
}

$peak = @{}
foreach ($c in $byCountry.Keys) {
    $peak[$c] = ($byCountry[$c].Values | Measure-Object -Maximum).Maximum
}

$significant = $peak.GetEnumerator() | Where-Object { $_.Value -ge 1 } | Sort-Object -Property Value -Descending
$out = @{}
foreach ($entry in $significant) { $out[$entry.Key] = $byCountry[$entry.Key] }
$out | ConvertTo-Json -Depth 5 | Set-Content $jsonPath -Encoding UTF8
Write-Host "  $($out.Keys.Count) significant producers (peak >= 1M bags)"

Write-Host "[3/3] Emitting coffee-usda.js..."

$regionMap = [ordered]@{
    'Brazil' = 'South America'; 'Colombia' = 'South America'; 'Peru' = 'South America'
    'Ecuador' = 'South America'; 'Venezuela' = 'South America'
    'Honduras' = 'Central America'; 'Mexico' = 'Central America'; 'Guatemala' = 'Central America'
    'El Salvador' = 'Central America'; 'Nicaragua' = 'Central America'; 'Costa Rica' = 'Central America'
    'Dominican Republic' = 'Central America'
    'Ethiopia' = 'Africa'; 'Uganda' = 'Africa'; "Cote d'Ivoire" = 'Africa'; 'Angola' = 'Africa'
    'Cameroon' = 'Africa'; 'Kenya' = 'Africa'; 'Congo (Kinshasa)' = 'Africa'; 'Tanzania' = 'Africa'
    'Madagascar' = 'Africa'
    'Vietnam' = 'Asia/Pacific'; 'Indonesia' = 'Asia/Pacific'; 'India' = 'Asia/Pacific'
    'Malaysia' = 'Asia/Pacific'; 'China' = 'Asia/Pacific'; 'Thailand' = 'Asia/Pacific'
    'Papua New Guinea' = 'Asia/Pacific'; 'Philippines' = 'Asia/Pacific'
}

$harvest = Get-Content $jsonPath -Raw | ConvertFrom-Json

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// coffee-usda.js - auto-generated by scripts/coffee-harvest/refresh.ps1')
[void]$sb.AppendLine('// Source: USDA FAS PSD (Production, Supply & Distribution database)')
[void]$sb.AppendLine('// License: U.S. Public Domain (OPEN Government Data Act)')
[void]$sb.AppendLine('// Unit: millions of 60kg bags; year label = USDA marketing-year start')
[void]$sb.AppendLine('// Do not hand-edit - regenerate to refresh. The multi-source composed')
[void]$sb.AppendLine('// dataset lives in src/data/coffee-harvest.js.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("export const USDA_FETCHED_ON = '$(Get-Date -Format 'yyyy-MM-dd')';")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// Country -> { region, peak, latest, production: { year: bags_millions } }')
[void]$sb.AppendLine('export const USDA_PRODUCERS = {')

$countriesInHarvest = $harvest.PSObject.Properties.Name
$ordered = $regionMap.Keys | Where-Object { $countriesInHarvest -contains $_ }

foreach ($country in $ordered) {
    $years = $harvest.$country.PSObject.Properties | Sort-Object { [int]$_.Name }
    $region = $regionMap[$country]
    $peakVal = ($years | Measure-Object -Property Value -Maximum).Maximum
    $latestYearProp = $years | Select-Object -Last 1
    $latestYear = [int]$latestYearProp.Name
    $latestVal = $latestYearProp.Value
    [void]$sb.AppendLine("  ""$country"": {")
    [void]$sb.AppendLine("    region: '$region',")
    [void]$sb.AppendLine("    peak: $peakVal,")
    [void]$sb.AppendLine("    latest: { year: $latestYear, bags: $latestVal },")
    [void]$sb.Append('    production: {')
    $parts = @()
    foreach ($y in $years) { $parts += "$($y.Name): $($y.Value)" }
    [void]$sb.Append(($parts -join ', '))
    [void]$sb.AppendLine(' },')
    [void]$sb.AppendLine('  },')
}
[void]$sb.AppendLine('};')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $utf8NoBom)
Write-Host "`nWrote $outPath ($($sb.Length) chars, $($ordered.Count) countries)"
